# -*- mode: ruby -*-
# vi: set ft=ruby :

# Plugin Vagrant - Azure
require 'vagrant-azure'

Vagrant.configure("2") do |config|

  config.vm.box = "azure-dummy"                             # Azure box dummy
  config.ssh.private_key_path = '~/.ssh/id_rsa'             # Indicamos ruta ssh clave privada

  ## Shared folders (necesario?)
  #config.vm.synced_folder ".", "/vagrant", type: "smb", smb_host: "192.168.1.51"  # Intento de crear enlace
  config.vm.synced_folder ".", "/vagrant", disabled: true   # Para no tener que compartirlas
  #config.vm.network :private_network, ip: "192.168.1.51"   

  # Configuramos las diferentes maquinas
  config.vm.define "maquina1" do |maquina1|
    #
    maquina1.vm.host_name = "maquina1"
    maquina1.vm.network "public_network", ip: "192.168.1.201"
    maquina1.vm.network "private_network", ip: "192.168.10.21"
    #
    maquina1.vm.provider "azure" do |az, override|  # Parametros para AZURE     
      # Variables de entorno
      az.tenant_id = ENV['AZURE_TENANT_ID'] 
      az.client_id = ENV['AZURE_CLIENT_ID'] 
      az.client_secret = ENV['AZURE_CLIENT_SECRET'] 
      az.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
  
      # Datos para la MV
      az.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'     # Imagen MV
      az.vm_name = 'ubuntucchito5m1'                                  # Nombre MV
      az.vm_size = 'Standard_B1s'                                     # Tamaño MV
      az.resource_group_name = 'Hito5ccv4'                            # Grupo de recursos
      #az.location = ''                                             # Azure location to build the VM -- defaults to westus
    end
  end
  
  config.vm.define "maquina2" do |maquina2|
    #
    maquina2.vm.host_name = "maquina2"
    maquina2.vm.network "public_network", ip: "192.168.1.202"
    maquina2.vm.network "private_network", ip: "192.168.10.22"
    #
    maquina2.vm.provider "azure" do |az, override|  # Parametros para AZURE     
      # Variables de entorno
      az.tenant_id = ENV['AZURE_TENANT_ID'] 
      az.client_id = ENV['AZURE_CLIENT_ID'] 
      az.client_secret = ENV['AZURE_CLIENT_SECRET'] 
      az.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
  
      # Datos para la MV
      az.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'     # Imagen MV
      az.vm_name = 'ubuntucchito5m2'                                  # Nombre MV
      az.vm_size = 'Standard_B1s'                                     # Tamaño MV
      az.resource_group_name = 'Hito5ccv4'                            # Grupo de recursos
      #az.location = ''                                             # Azure location to build the VM -- defaults to westus
    end
  end

  # Provisionamos cada maquina con el mismo playbook
  #config.vm.provision "ansible" do |ansible|  # Parametros para Ansible
    #ansible.playbook = "../provision/playbook.yml"
  #end
end 